{% set version = "0.5" %}

package:
  name: genrich
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/jsh58/Genrich/archive/v{{ version }}.tar.gz
  sha256: 88491354ad1149847ef80bfedf06478087142ac3d0f7b72ebd9779c455afb87a

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - Genrich -h

about:
  home: https://github.com/jsh58/Genrich
  license: MIT
  summary: Genrich is a peak-caller for genomic enrichment assays (e.g. ChIP-seq, ATAC-seq).

extra:
  identifiers:
    - biotools:genrich
